name: youtube_web_player
description: "A Flutter package that opens YouTube videos in a WebView."
version: 0.0.6
repository: https://github.com/ultra-rony/youtube_web_player
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
