name: youtube_web_player
description: "A Flutter package for seamless integration of YouTube videos in a native WebView, providing a smooth playback experience. Ideal for multimedia applications."
version: 1.0.8
repository: https://github.com/ultra-rony/youtube_web_player
homepage: https://rony.fun

topics: [youtube, youtube-player, ywp, player, video]

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: The flutter bloc package logo.
    path: screenshots/logo.png